version: '3.3'

services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - DEEPINFRA_API_KEY=${DEEPINFRA_API_KEY}

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`iiset.io`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=myresolver"

      - "traefik.http.routers.app-http.rule=Host(`iiset.io`)"
      - "traefik.http.routers.app-http.entrypoints=web"
      - "traefik.http.routers.app-http.middlewares=redirect-to-https"
      - "traefik.http.services.app.loadbalancer.server.port=3000"

      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.docker.network=iiset_app-network"

    volumes:
      - ./content/blog:/app/content/blog
      - ./public/blog:/app/public/blog
      - ./uploads:/app/uploads



    networks:
      - app-network
      - traefik
  app-stage:
    #    ports:
    #      - "3000:3000"
    container_name: app-stage
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.stage.local
    environment:
      - NODE_ENV=production
    volumes:
      - ./content/blog:/app/content/blog
      - ./public/blog:/app/public/blog
      - ./uploads:/app/uploads

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-stage.rule=Host(`stage.${HOST}`)"
      - "traefik.http.routers.app-stage.entrypoints=websecure"
      - "traefik.http.routers.app-stage.tls.certresolver=myresolver"

      - "traefik.http.routers.app-http.rule=Host(`stage.${HOST}`)"
      - "traefik.http.routers.app-http.entrypoints=web"
      - "traefik.http.routers.app-http.middlewares=redirect-to-https"
      - "traefik.http.services.app-stage.loadbalancer.server.port=3000"

      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
    networks:
      - app-network

  models:
    container_name: models
    build:
      context: Models
      dockerfile: Dockerfile
    networks:
      - app-network

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entryPoints.web.address=:80"
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${HOST}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.routers.dashboard.tls.certresolver=myresolver"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/etc/traefik/usersfile"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./usersfile:/etc/traefik/usersfile:ro"
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - app-network

  mongodb:
    environment:
       - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
       - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    container_name: mongodb
    image: mongo:7.0.17
    volumes:
      - iiset_mongodb_data:/data/db
    networks:
      - app-network

  mongodb-stage:
    ports:
          - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    container_name: mongodb-stage
    image: mongo:7.0.17
    volumes:
      - mongodb_data_stage:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:
  mongodb_data_stage:
  iiset_mongodb_data:

networks:
  app-network:
    driver: bridge

  traefik:
    external: true



